export const GET_FILTERED_RECIPES = 'GET_FILTERED_RECIPES';
export const GET_FILTERED_RECIPES_SUCCESS = 'GET_FILTERED_RECIPES_SUCCESS';
export const GET_FILTERED_RECIPES_ERROR = 'GET_FILTERED_RECIPES_ERROR';

export const GET_RANDOM_RECIPES = 'GET_RANDOM_RECIPES';
export const GET_RANDOM_RECIPES_SUCCESS = 'GET_RANDOM_RECIPES_SUCCESS';
export const GET_RANDOM_RECIPES_ERROR = 'GET_RANDOM_RECIPES_ERROR';

export const GET_RECIPE_BYID = 'GET_RECIPE_BYID';
export const GET_RECIPE_BYID_SUCCESS = 'GET_RECIPE_BYID_SUCCESS';
export const GET_RECIPE_BYID_ERROR = 'GET_RECIPE_BYID_ERROR';