export const GET_FILTERED_RECIPES = 'GET_FILTERED_RECIPES';
export const GET_FILTERED_RECIPES_SUCCESS = 'GET_FILTERED_RECIPES_SUCCESS';
export const GET_FILTERED_RECIPES_ERROR = 'GET_FILTERED_RECIPES_ERROR';
