export const GET_FILTERED_RECIPES = 'GET_FILTERED_RECIPES';
export const GET_FILTERED_RECIPES_SUCCESS = 'GET_FILTERED_RECIPES_SUCCESS';
export const GET_FILTERED_RECIPES_ERROR = 'GET_FILTERED_RECIPES_ERROR';

export const GET_RANDOM_RECIPES = 'GET_RANDOM_RECIPES';
export const GET_RANDOM_RECIPES_SUCCESS = 'GET_RANDOM_RECIPES_SUCCESS';
export const GET_RANDOM_RECIPES_ERROR = 'GET_RANDOM_RECIPES_ERROR';

export const UPDATE_RECIPES_ON_DELETE = 'UPDATE_RECIPES_ON_DELETE';

export const GET_RECIPE_BYID = 'GET_RECIPE_BYID';
export const GET_RECIPE_BYID_SUCCESS = 'GET_RECIPE_BYID_SUCCESS';
export const GET_RECIPE_BYID_ERROR = 'GET_RECIPE_BYID_ERROR';

export const UPDATE_RECIPE_ON_DELETE = 'UPDATE_RECIPE_ON_DELETE';

export const POST_RECIPE = 'POST_RECIPE';
export const POST_RECIPE_SUCCESS = 'POST_RECIPE_SUCCESS';
export const POST_RECIPE_ERROR = 'POST_RECIPE_ERROR';

export const PUT_RECIPE = 'PUT_RECIPE';
export const PUT_RECIPE_SUCCESS = 'PUT_RECIPE_SUCCESS';
export const PUT_RECIPE_ERROR = 'PUT_RECIPE_ERROR';

export const DELETE_RECIPE = 'DELETE_RECIPE';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';
